tokenizer_name: heziyevv/aze-bert-tokenizer-large
model_name: aze-ds-model-second
max_epochs: 10
learning_rate: 1e-4
batch_size: 256
eval_batch_size: 256
max_num_tokens: 256
bucket_name: azenews-bucket
