tokenizer_name: heziyevv/aze-bert-tokenizer-large
model_name: aze-ds-model-first
max_epochs: 1000
learning_rate: 1e-4
batch_size: 64
eval_batch_size: 64
max_num_tokens: 256
bucket_name: azenews-bucket
